import { useEffect, useMemo, useState } from "react";
import { getReports } from "../lib/dashboard";
import "../styles/dashboard.css";

type Report = {
  id: number;
  report_name: string;
  report_type: string;
  generated_at: string;
  generated_by: string;
  total_records: number;
};

export default function Reports() {
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState("All");

  useEffect(() => {
    loadReports();
  }, []);

  async function loadReports() {
    try {
      const data = await getReports();
      setReports(data as Report[]);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  }

  const filtered = useMemo(() => {
    if (filter === "All") return reports;
    return reports.filter((r) => r.report_type === filter);
  }, [reports, filter]);

  return (
    <div className="page">

      <div className="pageHeader">

        <div>
          <h1>📊 Reports Centre</h1>
          <p>Campaign Intelligence Reports</p>
        </div>

        <button className="primaryButton">
          Generate Report
        </button>

      </div>

      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))",
          gap: 20,
          marginBottom: 30,
        }}
      >

        <div className="statCard">
          <h3>{reports.length}</h3>
          <span>Total Reports</span>
        </div>

        <div className="statCard">
          <h3>
            {
              reports.filter(
                (r) => r.report_type === "Contacts"
              ).length
            }
          </h3>
          <span>Contact Reports</span>
        </div>

        <div className="statCard">
          <h3>
            {
              reports.filter(
                (r) => r.report_type === "Volunteer"
              ).length
            }
          </h3>
          <span>Volunteer Reports</span>
        </div>

        <div className="statCard">
          <h3>
            {
              reports.reduce(
                (sum, r) => sum + r.total_records,
                0
              )
            }
          </h3>
          <span>Total Records</span>
        </div>

      </div>

      <div
        style={{
          display: "flex",
          gap: 10,
          flexWrap: "wrap",
          marginBottom: 25,
        }}
      >

        {[
          "All",
          "Contacts",
          "Volunteer",
          "Events",
          "Broadcast",
          "Analytics",
        ].map((item) => (

          <button
            key={item}
            className="primaryButton"
            onClick={() => setFilter(item)}
          >
            {item}
          </button>

        ))}

      </div>

      <table className="dataTable">

        <thead>

          <tr>
            <th>Report</th>
            <th>Type</th>
            <th>Generated By</th>
            <th>Date</th>
            <th>Records</th>
            <th>Action</th>
          </tr>

        </thead>

        <tbody>

          {loading ? (

            <tr>
              <td colSpan={6}>
                Loading reports...
              </td>
            </tr>

          ) : (

            filtered.map((report) => (

              <tr key={report.id}>

                <td>{report.report_name}</td>

                <td>{report.report_type}</td>

                <td>{report.generated_by}</td>

                <td>
                  {new Date(
                    report.generated_at
                  ).toLocaleDateString()}
                </td>

                <td>{report.total_records}</td>

                <td>

                  <button
                    className="primaryButton"
                    style={{
                      padding: "6px 12px",
                    }}
                  >
                    Download
                  </button>

                </td>

              </tr>

            ))

          )}

        </tbody>

      </table>

    </div>
  );
}